### PR TITLE
On Prem Routing fixes

### PR DESCRIPTION
**Pull request by tarzzz**

### CODE REVIEW

**Comment by tarzzz** [comment]
@chriddyp Please review.

I was trying to use `basename` in router, but that doesn't seem to be working so I ended up adding `homeUrl` to the components separately.

Others are some generic fixes I observed while testing with on-prem.

**Comment by chriddyp** [comment]
On first pass, this looks good. What about the API requests, do their URLs need to be prefixed as well? I recall that I implemented those URLs using relative paths (e.g. `settings` instead of `/settings`) which would work if the home page is `/` or `/external-data-connector` but might not work if the page is `/external-data-connector/login`

**Comment by tarzzz** [comment]
>  What about the API requests, do their URLs need to be prefixed as well?

I do not think so, because I tested this branch with our onprem server and everything works as expected.

**Comment by chriddyp** [comment]
💃

**Pull request merged**
