### PR TITLE
Setup prettier

### LINKED ISSUE #475: setup prettier

### PR DESCRIPTION
**Pull request by n-riesco**
@mfix22 @nicolaskruchten
@tarzzz @shannonlal @kndungu 

I've noticed that `prettier` has an option to ignore files without a `pragma` (see [this commit](https://github.com/plotly/falcon-sql-client/commit/fa88c50b73711fd7db9a9a1180fd6130c68ae341) for an example of how it works).

I've also added `husky` to setup a git hook, so that `prettier` runs automatically before a `git commit`.

If you all are happy with this incremental approach, let's merge this PR.

Closes #475

### CODE REVIEW

**Comment by nicolaskruchten** [comment]
I would be more in favour of running it over a larger/complete set of files early on, otherwise it will make PR reviews in the future more challenging as we will have "ran prettier" interspersed with other commits...

**Comment by kndungu** [comment]
💯 

It's about time 🎆 

Suggestion: Consider adding `"arrowParens": "always"` to the Prettier config

Will turn 

```
const addOne = param => param + 1
```

To

```
const addOne = (param) => param + 1
```

**Comment by n-riesco** [comment]
@kndungu I can't believe I've missed that option! Of course, I'll add it.

**Comment by n-riesco** [comment]
@nicolaskruchten @kndungu @tarzzz Let's be pragmatic about the **temporary** use of pragmas. I'm not going to run `prettier` on the whole code base just before an on-prem release.

The benefit of having DawnLabs' contributions formatted right away outweighs the nuisance of adding a pragma.

**Comment by nicolaskruchten** [comment]
Since you asked for my feedback, I gave it: I favour the all or nothing
approach, whether your consider that pragmatic or not. That said, my
opinion doesn’t count any more than anyone else’s here: if others feel it’s
an improvement then let’s do it.

**Comment by n-riesco** [comment]
@mfix22 You see most people but me want to run `prettier` on the whole code base. I will do that after the on-prem release, but if you want to be able to use `prettier` with your contributions before, I'll merge this PR now, so that you can do so.

**Comment by n-riesco** [comment]
I'm closing since there is no interest in merging before the onprem release.

**Pull request closed without merging**
