### PR TITLE
Eslint remaining fixes

### PR DESCRIPTION
**Pull request by rmoestl**
@chriddyp these were the last ESLint problems in the code base. I thought activating the `no-trailing-spaces` rule would be nice, so I did. In case we don't need it, let's just discard the commit.

### CODE REVIEW

**Comment by chriddyp** [comment]
awesome stuff @rmoestl , thank you! 💃

**Comment by chriddyp** [comment]
now we can finally add eslint to our tests?

**Comment by rmoestl** [comment]
Thx @chriddyp. 
Yes, I guess we can add ESLint to tests now.

**Comment by rmoestl** [comment]
FYI @chriddyp: got my hands dirty enabling ESLint in tests, see https://github.com/plotly/falcon-sql-client/commit/16683236cf6b13dddd2b78eb5cd59f88824716e8

**Pull request merged**
