### PR TITLE
Update oauth token-save url

### LINKED ISSUE #227: Unable to Authorize with Plotly Cloud
When running falcon in the docker container, the OAuth callback fails with "Error: Please login to access this page."

Relevant logs:

```
{"name":"plotly-database-connector-logger","hostname":"0f44c726d23e","pid":24,"level":30,"msg":"Request: /oauth2/callback","time":"2017-11-09T13:26:31.816Z","v":0}
{"name":"plotly-database-connector-logger","hostname":"0f44c726d23e","pid":24,"level":30,"msg":"Request: /static/web-bundle.min.js?t=1510233991030","time":"2017-11-09T13:26:31.878Z","v":0}
{"name":"plotly-database-connector-logger","hostname":"0f44c726d23e","pid":24,"level":30,"msg":"Request: /oauth2/oauth2","time":"2017-11-09T13:26:32.784Z","v":0}
```

Screenshot of error:

screen shot 2017-11-09 at 8 23 50 am

### PR DESCRIPTION
**Pull request by tarzzz**
Updates Oauth issue mentioned in #227

### CODE REVIEW

**Comment by tarzzz** [comment]
cc: @n-riesco @snooc

**Comment by n-riesco** [comment]
I don't know how to test the onprem case.

@snooc would you be able to test if this PR fixes #227 for you?

**Comment by tarzzz** [comment]
@n-riesco I have checked these changes on our test on-prem server..

**Comment by n-riesco** [comment]
@tarzzz If I'm not mistaken, none of the tests in CircleCI can catch this issue. For that reason, we need @snooc (or someone else) to confirm the PR works using their own machines.

**Comment by tarzzz** [comment]
@n-riesco Yes, I am going to merge the PR but keep the related issue open until @snooc can confirm it is resolved.

**Comment by n-riesco** [comment]
:dancer: from me, but let's close #227 after we hear from @snooc.

**Pull request merged**
